networks:
  bezaforge-net:
    external: true

services:
  adguard:
    image: adguard/adguardhome:v0.107.77@sha256:e6f2b8bcda06064ab055b44933a4f0e983c35558b9cdb8d2e7ab1efcee36d890
    container_name: adguard
    restart: unless-stopped
    ports:
      - "10.10.20.20:53:53/tcp"
      - "10.10.20.20:53:53/udp"
      - "10.10.20.20:3053:3000/tcp"
    volumes:
      - /opt/bezaforge/adguard/work:/opt/adguardhome/work
      - /opt/bezaforge/adguard/conf:/opt/adguardhome/conf
    networks:
      - bezaforge-net
