networks:
  bezaforge-net:
    external: true

services:
  adguard:
    image: adguard/adguardhome:v0.107.71@sha256:92929135ced2554aaf94706f766a98ad348f211df61b0704e2db7e8498cc00b7
    container_name: adguard
    restart: unless-stopped
    ports:
      - "10.10.20.20:53:53/tcp"
      - "10.10.20.20:53:53/udp"
      - "10.10.20.20:3053:3000/tcp"
    volumes:
      - /opt/bezaforge/adguard/work:/opt/adguardhome/work
      - /opt/bezaforge/adguard/conf:/opt/adguardhome/conf
    networks:
      - bezaforge-net
