networks:
  bezaforge-net:
    external: true

services:
  adguard:
    image: adguard/adguardhome:v0.107.78@sha256:1ea34eafe5dc691007946e8eaab7bf46b0de9412f39213d8c06e48b53bf9a6c5
    container_name: adguard
    restart: unless-stopped
    ports:
      - "10.10.20.20:53:53/tcp"
      - "10.10.20.20:53:53/udp"
      - "10.10.20.20:3053:3000/tcp"
    volumes:
      - /opt/bezaforge/adguard/work:/opt/adguardhome/work
      - /opt/bezaforge/adguard/conf:/opt/adguardhome/conf
    networks:
      - bezaforge-net
