---
all:
  children:
    hypervisor_hosts:
      hosts:
        forge-hypervisor:
    docker_hosts:
      hosts:
        forge-ops:
    gpu_hosts:
      hosts:
        forge-ai:
    assistant_hosts:
      hosts:
        forge-brizza:
