networks:
  bezaforge-net:
    external: true

services:
  loki:
    image: grafana/loki:3.7.3@sha256:70b9f699fc9bb868b62f1cfd4f787dfa50242f1fd92e6089787d5d7daea75fe8
    container_name: loki
    restart: unless-stopped
    ports:
      - "10.10.20.20:3100:3100"
    volumes:
      - /opt/bezaforge/loki/config.yml:/etc/loki/config.yml:ro
      - /opt/bezaforge/loki/data:/loki
    command: -config.file=/etc/loki/config.yml
    networks:
      - bezaforge-net

  promtail:
    image: grafana/promtail:3.6.11@sha256:a761cb834cfaeee29745440d4884d6748f0a08d8f68928db1d707018c1dcfbe9
    container_name: promtail
    restart: unless-stopped
    user: root
    volumes:
      - /opt/bezaforge/loki/promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - bezaforge-net
