---
- name: restart prometheus
  community.docker.docker_compose_v2:
    project_src: "{{ bezaforge_root }}/prometheus"
    state: present
    recreate: always

- name: restart grafana
  community.docker.docker_compose_v2:
    project_src: "{{ bezaforge_root }}/grafana"
    state: present
    recreate: always

- name: restart loki
  community.docker.docker_compose_v2:
    project_src: "{{ bezaforge_root }}/loki"
    state: present
    recreate: always
